### ISSUE TITLE
Robustness of the scraper

### ISSUE THREAD

**Issue by DeependraD** [tesla1volt/CalenderParser#1]
Dear bro, this app seems interesting and very useful too. But have you verified the accuracy of the output date? Because, I once constructed this (https://github.com/DeependraD/BS-2-AD-lookup-table) only to fail in having expected output. Also, I am wondering what the target site uses for conversion. Do they have a lookup table or so? If thats the case, lets develop that and forget reliance. I already have a template if youre interested.

**Comment by tesla1volt** [comment]
Hello bro, in this app actually date from start to end of the year of one year is converted from English to Nepali using rajancalander.com.np. I have used the output of this app for another project so I am pretty confident the output is correct (given the output from the website is correct). I implemented REST api in this project https://github.com/tesla1volt/microservice

**Comment by DeependraD** [comment]
Nice concept. Sending request and grabbing output on demand is great. I will try mimic your idea in generating a monthwise lookup table. This will well serve my petty purpose, though. Thanks.
